language: csharp
sudo: required
dotnet: 2.2.101
dist: xenial
before_install:
  - chmod +x fake.sh
script:
  ./fake.sh
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1